myName = input("What's you name? ")
myAge = input("How old are you? ")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit? ")
print("OF COURSE YOU DO!")

print() #This is to add a blank line to add space between the questions and the answers
print("So, you are")
print(myName) #To print the name of the user
print("and are the ripe old age of")
print(myAge) #To print the age of the user
print("and clearly think that Replit is")
print(replit)

myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order" + myLunch)
print("as soon as possible!")

#Day 2 Challenge 
#print("Definitely not a Phishing Scam")
#print()
#input("Your Name")
#print("Thanks for logging in")
#print(myName)
#cardNumber = input("What is your credit card number?")
#print("Thanks, I definitely wont put")
#print("cardNumber")
#print("into Amazon and order anything weird")
#print()
#print("Promise")
#maidenName input("What is your Mother's maiden name? ")
#print()
#print("That's cool, I just wanted to know that")
#print(maidenName)
#print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

#My Solution to Day 2 Challenge
print("Definitely not a Phishing Scam")
print()
myName = input("Your Name")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")